server:
  port: 9001
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}
    fetch-registry: true
    registry-fetch-interval-seconds: 5
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1

        - id: fias-service
          uri: lb://fias-service
          predicates:
            - Path=/fias-service/**
          filters:
            - StripPrefix=1
