server:
  port: 0
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9005/shop
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}
    fetch-registry: false