server:
  port: 0
spring:
  application:
    name: fias-service
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}
    fetch-registry: true